#!/bin/sh

# A bug in Crytic-Compile (dependency of Echidna) causes
# Echidna to fail for contracts that produce compilation 
# warnings. Using this as a wrapper for Solc sends all
# warnings (and errors too!) to /dev/null as a workaround
~/.solcx/solc-v0.4.26 $@ 2>/dev/null
