name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: snickerbockers/submodules-init@v4
    - uses: satackey/action-docker-layer-caching@v0.0.11
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rvsc:$(date +%s)
